# Generated by Django 5.2.14 on 2026-06-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='credited',
            field=models.BooleanField(default=False),
        ),
    ]
