# Generated by Django 5.2.14 on 2026-06-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_deposit_credited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='credited',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='tx_hash',
        ),
        migrations.AddField(
            model_name='deposit',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='deposit_proofs/'),
        ),
    ]
