# Generated by Django 5.2.14 on 2026-06-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_deposit_credited_remove_deposit_tx_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='credited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/'),
        ),
    ]
