# Generated by Django 5.2.14 on 2026-06-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_referralbonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
