# Generated by Django 5.2.11 on 2026-06-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_withdrawal_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
