# Generated by Django 5.2.11 on 2026-06-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_withdrawal_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
