# Generated by Django 5.2.14 on 2026-06-02 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_referrer_interestwallet_referral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bonus_rate', models.DecimalField(decimal_places=3, max_digits=5)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.referral')),
            ],
        ),
    ]
