# Generated by Django 5.2.14 on 2026-06-03 14:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_referraldeposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_interest_claim',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='bonus_rate',
        ),
        migrations.AlterField(
            model_name='interestwallet',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='referraldeposit',
            name='bonus_rate',
            field=models.DecimalField(decimal_places=3, default=0.01, max_digits=5),
        ),
    ]
