# Generated by Django 5.2.14 on 2026-06-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_profile_last_interest_claim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referraldeposit',
            name='claimed_bonus',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
    ]
